### Normal Case
GET http://localhost:8081/order/order_1


### Closed Projections
GET http://localhost:8081/projection/order/detail/order_1


### Open Projections
GET http://localhost:8081/projection/item/detail/order_1


### DTO Projections
GET http://localhost:8081/projection/succeed/orders


### Dynamic Projections
GET http://localhost:8081/projection/orders/dynamic/order_1?tidy=true


### ResultMapping - DTO
GET http://localhost:8081/projection/order/total/record


### ResultMapping - Interface
GET http://localhost:8081/projection/order/total/interface


### Web Layer
GET http://localhost:8081/demo/web/layer/order_1